#!/usr/bin/env python3
"""Regenerates native/src/platform/linux/AppIcon.h from assets/icon.png.
Run manually whenever the icon changes - not part of the normal build.

    python3 tools/png_to_header.py assets/icon.png \\
        native/src/platform/linux/AppIcon.h 64

Decodes a plain (non-interlaced, RGBA8) PNG using only the Python stdlib
(zlib), downscales it with simple nearest-neighbor sampling, and emits a
C++ header with the raw ARGB32 bytes baked in as a static array - so
SniTray can send IconPixmap over D-Bus with zero runtime PNG-decoding
dependency (no gdk-pixbuf, no libpng). Only handles the specific PNG
format icon.png is actually in (8-bit RGBA, no interlacing) - not a
general-purpose PNG decoder."""
import struct
import sys
import zlib


def read_png_rgba(path):
    with open(path, "rb") as f:
        data = f.read()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError("not a PNG")
    pos = 8
    width = height = bitdepth = colortype = interlace = None
    idat = b""
    while pos < len(data):
        length = struct.unpack(">I", data[pos:pos + 4])[0]
        ctype = data[pos + 4:pos + 8]
        chunk = data[pos + 8:pos + 8 + length]
        if ctype == b"IHDR":
            width, height, bitdepth, colortype, _, _, interlace = struct.unpack(">IIBBBBB", chunk)
        elif ctype == b"IDAT":
            idat += chunk
        elif ctype == b"IEND":
            break
        pos += 12 + length
    if bitdepth != 8 or colortype != 6 or interlace != 0:
        raise ValueError(f"unsupported PNG format: bitdepth={bitdepth} colortype={colortype} interlace={interlace}")

    raw = zlib.decompress(idat)
    stride = width * 4
    out = bytearray(width * height * 4)
    prev = bytearray(stride)
    pos = 0
    for y in range(height):
        filt = raw[pos]
        pos += 1
        line = bytearray(raw[pos:pos + stride])
        pos += stride
        if filt == 0:
            pass
        elif filt == 1:  # Sub
            for x in range(4, stride):
                line[x] = (line[x] + line[x - 4]) & 0xFF
        elif filt == 2:  # Up
            for x in range(stride):
                line[x] = (line[x] + prev[x]) & 0xFF
        elif filt == 3:  # Average
            for x in range(stride):
                a = line[x - 4] if x >= 4 else 0
                b = prev[x]
                line[x] = (line[x] + (a + b) // 2) & 0xFF
        elif filt == 4:  # Paeth
            for x in range(stride):
                a = line[x - 4] if x >= 4 else 0
                b = prev[x]
                c = prev[x - 4] if x >= 4 else 0
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                pred = a if pa <= pb and pa <= pc else (b if pb <= pc else c)
                line[x] = (line[x] + pred) & 0xFF
        else:
            raise ValueError(f"unsupported filter type {filt}")
        out[y * stride:(y + 1) * stride] = line
        prev = line
    return bytes(out), width, height


def downscale_nearest(pixels, src_w, src_h, dst_w, dst_h):
    out = bytearray(dst_w * dst_h * 4)
    for dy in range(dst_h):
        sy = dy * src_h // dst_h
        for dx in range(dst_w):
            sx = dx * src_w // dst_w
            si = (sy * src_w + sx) * 4
            di = (dy * dst_w + dx) * 4
            out[di:di + 4] = pixels[si:si + 4]
    return bytes(out)


def main():
    src, dst_header, size = sys.argv[1], sys.argv[2], int(sys.argv[3])
    pixels, w, h = read_png_rgba(src)
    small = downscale_nearest(pixels, w, h, size, size)

    # StatusNotifierItem's IconPixmap wants ARGB32, network byte order
    # (big-endian 0xAARRGGBB per pixel) - our decoded data is RGBA bytes,
    # so repack per pixel rather than just reading it as RGBA.
    argb = bytearray(len(small))
    for i in range(0, len(small), 4):
        r, g, b, a = small[i:i + 4]
        argb[i:i + 4] = bytes([a, r, g, b])

    with open(dst_header, "w") as f:
        f.write("// Generated by png_to_header.py from assets/icon.png - do not edit by hand.\n")
        f.write("#pragma once\n\n#include <cstdint>\n\nnamespace nativeui {\n\n")
        f.write(f"constexpr int kAppIconSize = {size};\n")
        f.write("constexpr uint8_t kAppIconArgb32[] = {\n")
        for i in range(0, len(argb), 16):
            f.write("    " + ", ".join(str(b) for b in argb[i:i + 16]) + ",\n")
        f.write("};\n\n} // namespace nativeui\n")
    print(f"wrote {dst_header}: {size}x{size}, {len(argb)} bytes")


if __name__ == "__main__":
    main()
